# -*- coding: utf-8 -*-
"""PokémonMongo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nM7b8A2SSOXZ5CaApcgXVE9pD_BsJHul

# Consultas
"""

import os
!pip install pymongo
from pymongo import MongoClient
import datetime
from bson.objectid import ObjectId

mongo_url = "mongodb+srv://senac:senac@pokedex.n18knsm.mongodb.net/?retryWrites=true&w=majority&appName=Pokedex"
client = MongoClient(mongo_url)

db = client["Pokedex"]

### Buscando por 1 Pokemon
print("\n##### Buscando um Pokémon por nome #####")
match = {"nome_pokemon": "Rockruff"}

for pokemon in db.pokemons.find(match):
    print(pokemon)

### Buscando por vários Pokemons
print("\n##### Buscando Pokémon(s) por habilidade #####")
match = {"habilidades.nome": "Overgrow"}

for pokemon in db.pokemons.find(match):
    print(pokemon)

### Buscando por vários conteúdos
print("\n##### Buscando vários conteúdos #####")
match = {"tipo": { "$in": ["Grass", "Water"]}}

for pokemon in db.pokemons.find(match):
  print(pokemon)

### Buscando com OR
print("\n##### Busca OR #####")
match = {"$or": [{"efetividade.Fly": 0.5},{"efetividade.Psy": 1.0}]}

for pokemon in db.pokemons.find(match):
    print(pokemon)

### Buscando em um array
print("\n##### Buscando Pokémon(s) por tipo #####")
match = {"tipo": "Poison"}

for pokemon in db.pokemons.find(match):
    print(pokemon)

print("\n##### Buscando Pokémon(s) por tipos #####")
match = {"tipo": {"$in": ["Fire", "Dragon"]}}

for pokemon in db.pokemons.find(match):
    print(pokemon)

print("\n##### Buscando Pokémon(s) por quantidade de tipos #####")
match = {"tipo": {"$size": 2}}

for pokemon in db.pokemons.find(match):
    print(pokemon)

### Buscando em um array de objetos
print("\n##### Buscando Pokémon(s) por habilidade #####")
match = {"habilidades.nome": "Static"}

for pokemon in db.pokemons.find(match):
    print(pokemon)

print("\n##### Buscando Pokémon(s) por habilidade e descrição  #####")
match = {"habilidades": {"$elemMatch": {"nome": "Overgrow", "descricao": "Powers up Grass-type moves in a pinch."}}}

for pokemon in db.pokemons.find(match):
    print(pokemon)

print("\n##### Buscando Pokémon(s) que contenha 'powers' em sua descrição #####")
match = {"habilidades.descricao": {"$regex": "powers", "$options": "i"}}

for pokemon in db.pokemons.find(match):
    print(pokemon)